# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            I-No Liao
tagline:          '廖以諾'
description:      'Learn and live'
url:              

# For GitHub
baseurl:          /portfolio
# For local development
# baseurl:          /portfolio/

profile:          /assets/ProfilePicture.jpg

author:
  name:           'I-No Liao'
  url:            

# paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/INoLiao
 
plugins:
  - jekyll-paginate
  - jekyll-gist
