# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            I-No Liao
tagline:          '廖以諾'
description:      'Learn and live'

# For GitHub
# baseurl:          /portfolio
# For local development
# baseurl:          /portfolio/
# For domain inoliao.info
url:              inoliao.info

profile:          /assets/ProfilePicture.jpg
resume:           /assets/INo_CV_190625.pdf

author:
  name:           'I-No Liao'

# paginate:         5

# Custom vars
version:          1.0.0

github:           
  repo:           https://github.com/INoLiao
 
plugins:
  - jekyll-paginate
  - jekyll-gist
